version: "3"
services:
  # APP  ***************************************************************************************
  todo:
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017



